base: 
  build: ./apiserver
  links: 
    - db 
    - eureka 
eureka: 
   build: ./eurekaserver
   ports: 
     - "8010:8010"
db:
   build: ./dbserver 
   volumes: 
    - /home/vagrant/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
   ports: 
     - "3306:3306"
   environment: 
     MYSQL_ROOT_PASSWORD: password
